version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password

    EC2_HOST: /myapp/ec2/host
    EC2_USER: /myapp/ec2/user
    EC2_SSH_KEY: /myapp/ec2/shh_key

    SONAR_HOST_URL: /myapp/sonar/url
    SONAR_TOKEN: /myapp/sonarqube/codebuild-sonar-token
    GITHUB_TOKEN: /myapp/github/pat-token

phases:

  install:
    commands:
      - echo "Preparing SSH key..."
      - echo "$EC2_SSH_KEY" > key.pem
      - chmod 600 key.pem
      - export SSH_CMD="ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST"

  pre_build:
    commands:
      - echo "Cloning fresh repository in EC2..."
      - |
        $SSH_CMD "sudo rm -rf ~/project && \
                  git clone https://github.com/yojan1226/swiggy-DevOps-Project.git ~/project"

      - echo "Installing NPM dependencies..."
      - |
        $SSH_CMD "cd ~/project/swiggy-project && npm install"

      - echo "Running OWASP Dependency-Check..."
      - |
        $SSH_CMD "
          mkdir -p ~/dependency-check-reports && \
          dependency-check \
            --scan ~/project/swiggy-project \
            --out ~/dependency-check-reports/owasp-report \
            --data ~/dependency-check-data \
            --noupdate \
            --disableVersionCheck \
            || echo 'OWASP warnings ignored'
        "

      - echo "Running SonarQube Scanner..."
      - |
        $SSH_CMD "cd ~/project/swiggy-project && \
                  sonar-scanner \
                    -Dsonar.projectKey=swiggy-react-app \
                    -Dsonar.sources=. \
                    -Dsonar.host.url=$SONAR_HOST_URL \
                    -Dsonar.login=$SONAR_TOKEN"

  build:
    commands:
      - echo "Running Trivy filesystem scan..."
      - |
        $SSH_CMD "trivy fs --exit-code 1 \
                  --severity HIGH,CRITICAL \
                  ~/project/swiggy-project || true"

      - echo "Building React project..."
      - |
        $SSH_CMD "cd ~/project/swiggy-project && npm run build"

      - echo "Logging into DockerHub..."
      - |
        $SSH_CMD "echo \"$DOCKER_REGISTRY_PASSWORD\" \
                  | docker login -u \"$DOCKER_REGISTRY_USERNAME\" --password-stdin"

      # 🔹 Build image with fully-resolved name (important!)
      - echo "Building Docker image..."
      - |
        $SSH_CMD 'cd ~/project/swiggy-project && docker build -t '"${DOCKER_REGISTRY_USERNAME}"'/swiggy:latest .'


      - echo "Pushing latest image..."
      - |
        $SSH_CMD 'docker push '"${DOCKER_REGISTRY_USERNAME}"'/swiggy:latest'

  post_build:
    commands:
      - echo "Scanning pushed image with Trivy..."
      - |
        $SSH_CMD "trivy image --exit-code 1 \
                 --severity HIGH,CRITICAL \
                 ${DOCKER_REGISTRY_USERNAME}/swiggy:latest || true"

      - echo "Copying OWASP report back to CodeBuild..."
      - |
        scp -o StrictHostKeyChecking=no -i key.pem \
        $EC2_USER@$EC2_HOST:~/dependency-check-reports/owasp-report/dependency-check-report.html \
        .

      - echo "Generating image version tag..."
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - echo "IMAGE_TAG = $IMAGE_TAG"

      # 🔹 Tag + push versioned image (now succeeds)
      - echo "Tagging & pushing versioned Docker image..."
      - |
        $SSH_CMD 'docker tag '"${DOCKER_REGISTRY_USERNAME}"'/swiggy:latest '"${DOCKER_REGISTRY_USERNAME}"'/swiggy:'"${IMAGE_TAG}"' && \
                  docker push '"${DOCKER_REGISTRY_USERNAME}"'/swiggy:'"${IMAGE_TAG}"''

      # 🔹 Update Kubernetes manifest in GitHub
      - echo "Updating Kubernetes deployment.yaml in GitHub..."
      - |
        $SSH_CMD "
          cd ~/project && \

          git config user.email 'codebuild@aws' && \
          git config user.name 'AWS CodeBuild' && \

          sed -i \"s|image: honey120ar/swiggy:.*|image: honey120ar/swiggy:${IMAGE_TAG}|\" k8-manifest/deployment.yaml && \

          git add k8-manifest/deployment.yaml && \
          git commit -m 'Update image tag to ${IMAGE_TAG} from CodeBuild' || true && \

          git remote set-url origin https://${GITHUB_TOKEN}@github.com/yojan1226/swiggy-DevOps-Project.git && \
          git push origin HEAD:main
        "

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
