version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_URL: /myapp/docker-credentials/docker_registry_url
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password

    EC2_HOST: /myapp/ec2/host
    EC2_USER: /myapp/ec2/user
    EC2_SSH_KEY: /myapp/ec2/shh_key

    SONAR_HOST_URL: /myapp/sonar/url
    SONAR_TOKEN: /myapp/sonarqube/codebuild-sonar-token

phases:
  install:
    commands:
      - echo "Starting build on EC2 runner..."
      - echo "$EC2_SSH_KEY" > key.pem
      - chmod 600 key.pem
      - export SSH_CMD="ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST"

  pre_build:
    commands:
      - echo "Cloning or updating project dynamically..."
      - $SSH_CMD "if [ -d ~/project ]; then cd ~/project && git pull; else git clone https://github.com/yojan1226/swiggy-DevOps-Project.git ~/project; fi"

      - echo "Installing NPM dependencies..."
      - $SSH_CMD "cd ~/project && npm install"

      - echo "Running OWASP Dependency Check..."
      - $SSH_CMD "dependency-check --scan ~/project --out ~/reports/owasp-report"

      - echo "Running SonarQube Scan..."
      - $SSH_CMD "sonar-scanner \
          -Dsonar.projectKey=my-react-app \
          -Dsonar.sources=~/project \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN"

  build:
    commands:
      - echo "Running Trivy File System Scan..."
      - $SSH_CMD "trivy fs --exit-code 1 --severity HIGH,CRITICAL ~/project"

      - echo "Building React App..."
      - $SSH_CMD "cd ~/project && npm run build"

      - echo "Logging into Docker registry..."
      - $SSH_CMD "echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin $DOCKER_REGISTRY_URL"

      - echo "Building Docker image..."
      - $SSH_CMD "cd ~/project && docker build -t $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/react-app:latest ."

      - echo "Pushing Docker image..."
      - $SSH_CMD "docker push $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/react-app:latest"

  post_build:
    commands:
      - echo "Scanning built Docker image with Trivy..."
      - $SSH_CMD "trivy image --exit-code 1 --severity HIGH,CRITICAL $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/react-app:latest"

      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
