version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_URL: /myapp/docker-credentials/docker_registry_url   # docker.io
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username        # honey120ar
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password

    EC2_HOST: /myapp/ec2/host
    EC2_USER: /myapp/ec2/user
    EC2_SSH_KEY: /myapp/ec2/shh_key

    SONAR_HOST_URL: /myapp/sonar/url
    SONAR_TOKEN: /myapp/sonarqube/codebuild-sonar-token

phases:
  install:
    commands:
      - echo "Starting build on EC2 runner..."
      - echo "$EC2_SSH_KEY" > key.pem
      - chmod 600 key.pem

      - export SSH_CMD="ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST"

  pre_build:
    commands:
      - echo "🔥 Fresh cloning repository into EC2..."
      - |
        $SSH_CMD "sudo rm -rf ~/project && \
                  git clone https://github.com/yojan1226/swiggy-DevOps-Project.git ~/project"

      - echo "📦 Installing NPM dependencies..."
      - |
        $SSH_CMD "cd ~/project/swiggy-project && npm install"

      - echo "🛡 Running OWASP Dependency-Check..."
      - |
        $SSH_CMD "mkdir -p ~/dependency-check-reports ~/dependency-check-data && \
                  dependency-check \
                    --scan ~/project/swiggy-project \
                    --out ~/dependency-check-reports/owasp-report \
                    --data ~/dependency-check-data \
                    --noupdate || echo 'OWASP warnings ignored'"

      - echo "🔍 Running SonarQube Scan..."
      - |
        $SSH_CMD "cd ~/project/swiggy-project && \
                  sonar-scanner \
                    -Dsonar.projectKey=my-react-app \
                    -Dsonar.sources=. \
                    -Dsonar.host.url=$SONAR_HOST_URL \
                    -Dsonar.login=$SONAR_TOKEN"

  build:
    commands:
      - echo "🧪 Running Trivy FS Scan..."
      - |
        $SSH_CMD "trivy fs --exit-code 1 \
                  --severity HIGH,CRITICAL \
                  ~/project/swiggy-project || true"

      - echo "⚛️ Building React App..."
      - |
        $SSH_CMD "cd ~/project/swiggy-project && npm run build"

      - echo "🔐 Logging into DockerHub..."
      - |
        $SSH_CMD "echo \"$DOCKER_REGISTRY_PASSWORD\" | docker login -u \"$DOCKER_REGISTRY_USERNAME\" --password-stdin"

      - echo "🐳 Building Docker image..."
      - |
        $SSH_CMD "cd ~/project/swiggy-project && \
                  docker build -t $DOCKER_REGISTRY_USERNAME/swiggy:latest ."

      - echo "📤 Pushing Docker image..."
      - |
        $SSH_CMD "docker push $DOCKER_REGISTRY_USERNAME/swiggy:latest"

  post_build:
    commands:
      - echo "🔍 Scanning Docker image with Trivy..."
      - |
        $SSH_CMD "trivy image --exit-code 1 \
                  --severity HIGH,CRITICAL \
                  $DOCKER_REGISTRY_USERNAME/swiggy:latest || true"

      - echo "📥 Copying OWASP reports to CodeBuild..."
      - |
        scp -o StrictHostKeyChecking=no -i key.pem \
            $EC2_USER@$EC2_HOST:~/dependency-check-reports/* .

      - echo "🎉 Build completed successfully!"

artifacts:
  files:
    - '**/*'
